(function(root){
 const value=cards=>{let total=cards.reduce((s,c)=>s+Math.min(c.r,10),0),aces=cards.filter(c=>c.r===1).length;let soft=false;while(aces--&&total+10<=21){total+=10;soft=true}return {total,soft}};
 function shoe(rng=Math.random){const deck=[];for(let d=0;d<6;d++)for(let s=0;s<4;s++)for(let r=1;r<=13;r++)deck.push({r,s});for(let i=deck.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]}return deck}
 const fresh=coins=>({version:1,coins,phase:'bet',dealer:[],hands:[],active:0,deck:[],message:'Choose your stake. The table is yours.'});
 const draw=g=>{if(!g.deck.length)g.deck=shoe();return g.deck.pop()};
 const natural=h=>!h.split&&h.cards.length===2&&value(h.cards).total===21;
 function settle(g){const dt=value(g.dealer).total,dn=g.dealer.length===2&&dt===21;let payout=0;for(const h of g.hands){const pt=value(h.cards).total;let returned=0;if(pt>21){h.result='Bust'}else if(natural(h)&&dn){returned=h.bet;h.result='Push'}else if(dn){h.result='Dealer blackjack'}else if(natural(h)){returned=h.bet*2.5;h.result='Blackjack · pays 3:2'}else if(dt>21||pt>dt){returned=h.bet*2;h.result='Win · pays 1:1'}else if(pt===dt){returned=h.bet;h.result='Push'}else h.result='Dealer wins';h.returned=returned;payout+=returned;h.status='done'}g.coins+=payout;g.phase='done';g.message='Round complete · '+payout+' coins returned.';return g}
 function advance(g){while(g.active<g.hands.length&&g.hands[g.active].status!=='play')g.active++;if(g.active<g.hands.length)return g;g.phase='dealer';if(g.hands.some(h=>value(h.cards).total<=21&&!natural(h)))while(value(g.dealer).total<17)g.dealer.push(draw(g));return settle(g)}
 function deal(g,bet,deck){if(!['bet','done'].includes(g.phase)||!Number.isSafeInteger(bet)||bet<2||bet%2||bet>g.coins)return false;g.coins-=bet;g.deck=deck?[...deck]:shoe();g.dealer=[];g.hands=[{cards:[],bet,status:'play',split:false}];g.active=0;g.phase='play';const h=g.hands[0];h.cards.push(draw(g));g.dealer.push(draw(g));h.cards.push(draw(g));g.dealer.push(draw(g));g.message='Your move.';if(natural(h)||value(g.dealer).total===21)settle(g);else if(value(h.cards).total===21){h.status='stand';advance(g)}return true}
 function legal(g){const h=g.hands[g.active];const play=g.phase==='play'&&h?.status==='play';return {hit:play,stand:play,double:play&&h.cards.length===2&&g.coins>=h.bet,split:play&&h.cards.length===2&&h.cards[0].r===h.cards[1].r&&g.hands.length<4&&g.coins>=h.bet}}
 function act(g,action){if(!legal(g)[action])return false;let h=g.hands[g.active];if(action==='hit'){h.cards.push(draw(g));if(value(h.cards).total>=21){h.status=value(h.cards).total>21?'bust':'stand';advance(g)}}else if(action==='stand'){h.status='stand';advance(g)}else if(action==='double'){g.coins-=h.bet;h.bet*=2;h.doubled=true;h.cards.push(draw(g));h.status=value(h.cards).total>21?'bust':'stand';advance(g)}else{g.coins-=h.bet;const ace=h.cards[0].r===1;const other={cards:[h.cards.pop()],bet:h.bet,status:'play',split:true};h.split=true;h.cards.push(draw(g));other.cards.push(draw(g));g.hands.splice(g.active+1,0,other);if(ace){h.status=other.status='stand';h.splitAces=other.splitAces=true}else{if(value(h.cards).total===21)h.status='stand';if(value(other.cards).total===21)other.status='stand'}advance(g)}return true}
 function restore(raw,coins){try{if(!raw||raw.version!==1||!['bet','play','done'].includes(raw.phase))return fresh(coins);const card=c=>Number.isInteger(c.r)&&c.r>=1&&c.r<=13&&Number.isInteger(c.s)&&c.s>=0&&c.s<4;if(!Array.isArray(raw.deck)||raw.deck.length>312||!raw.deck.every(card)||!Array.isArray(raw.dealer)||raw.dealer.length>22||!raw.dealer.every(card)||!Array.isArray(raw.hands)||raw.hands.length>4||!raw.hands.every(h=>Array.isArray(h.cards)&&h.cards.length>=2&&h.cards.length<=22&&h.cards.every(card)&&Number.isSafeInteger(h.bet)&&h.bet>=2&&h.bet%2===0&&['play','stand','bust','done'].includes(h.status)))return fresh(coins);if(raw.phase==='play'&&(!Number.isInteger(raw.active)||!raw.hands[raw.active]||raw.hands[raw.active].status!=='play'||raw.dealer.length!==2))return fresh(coins);return {...raw,coins}}catch{return fresh(coins)}}
 function chipValues(coins){const balance=Number.isSafeInteger(coins)&&coins>=0?coins:0;const steps=[2,4,6,10,20,50,100,200,500,1000,2000,5000,10000,20000,50000,100000,200000,500000,1000000,2000000,5000000,10000000,20000000,50000000];const chosen=[2];for(const fraction of [.1,.2,.5]){const desired=Math.max(2,balance*fraction);let next=steps.filter(n=>n<=desired&&n>chosen.at(-1)).at(-1);if(!next)next=steps.find(n=>n>chosen.at(-1));chosen.push(next)}return chosen}
 root.RangeLensBlackjack={advance,settle,chipValues,value,shoe,fresh,deal,legal,act,restore};if(typeof module!=='undefined')module.exports=root.RangeLensBlackjack;
})(globalThis);
