(()=>{
 const B=RangeLensBlackjack,C=Stillwater,$=id=>document.getElementById(id),key='range-lens-stillwater-v1';let wallet,g,blocked=false,presentation=null,timer=null,epoch=0,seen=new Set();
 function load(){try{const raw=JSON.parse(localStorage.getItem(key));wallet=C.restore(raw);g=B.restore(raw?.blackjack,wallet.coins)}catch{wallet=C.fresh();g=B.fresh(0)}}
 function save(){wallet.coins=g.coins;wallet.blackjack=g;try{localStorage.setItem(key,JSON.stringify(wallet));$('save-state').textContent='Wallet & round saved on this device'}catch{blocked=true;$('save-state').textContent='Save unavailable. Do not bet until storage is available.'}}
 const ranks=['','A','2','3','4','5','6','7','8','9','10','J','Q','K'],suits=['♠','♥','♦','♣'];
 function card(c,hidden,id){const el=document.createElement('div');el.className='card'+(hidden?' back':[1,2].includes(c.s)?' red':'');const token=id+':'+c.r+':'+c.s+':'+hidden;if(seen.has(token))el.style.animation='none';seen.add(token);el.setAttribute('role','img');el.setAttribute('aria-label',hidden?'Dealer hole card':ranks[c.r]+' '+['spades','hearts','diamonds','clubs'][c.s]);if(!hidden){const rank=document.createElement('span'),suit=document.createElement('span');rank.textContent=ranks[c.r];suit.className='suit';suit.textContent=suits[c.s];el.append(rank,suit)}return el}
 function render(){
  const animating=!!presentation,playing=g.phase==='play',locked=blocked||playing||animating;const coins=presentation?.coins??g.coins,dealer=g.dealer.slice(0,presentation?.dealerCount??g.dealer.length),holeHidden=presentation?presentation.hideHole:playing;
  if(playing)$('bet').value=String(g.hands[g.active].bet);$('coins').textContent=coins;const username=wallet.username||'Angler';$('player-name').textContent=username;$('dealer-cards').replaceChildren();dealer.forEach((c,i)=>$('dealer-cards').append(card(c,holeHidden&&i===1,'dealer'+i)));$('dealer-total').textContent=!dealer.length?'—':holeHidden?(dealer.length>1?B.value([dealer[0]]).total+' + ?':B.value(dealer).total):B.value(dealer).total;
  $('hands').replaceChildren();g.hands.forEach((h,i)=>{const visible=h.cards.slice(0,presentation?.handCounts[i]??h.cards.length),box=document.createElement('section');box.className='hand'+(playing&&i===g.active?' active':'');const label=document.createElement('div');label.className='seat-label';label.textContent=(g.hands.length>1?username+' · HAND '+(i+1):username+' · YOUR HAND')+' · '+h.bet+' coins';const total=document.createElement('span'),v=B.value(visible);total.textContent=visible.length?(v.soft?'Soft ':'')+v.total+(h.doubled?' · doubled':''):'—';label.append(total);const cards=document.createElement('div');cards.className='cards';visible.forEach((c,j)=>cards.append(card(c,false,'hand'+i+'card'+j)));box.append(label,cards);if(!animating&&(h.result||h.status!=='play')){const result=document.createElement('div');result.className='hand-result';result.textContent=h.result?h.result+' · '+h.returned+' returned':h.status==='bust'?'Bust':'Standing';box.append(result)}$('hands').append(box)});
  $('round-message').textContent=presentation?.message??g.message;const legal=B.legal(g);for(const id of ['hit','stand','double','split'])$(id).disabled=blocked||animating||!legal[id];const bet=Number($('bet').value),denominations=B.chipValues(coins);document.querySelectorAll('[data-stake]').forEach((chip,i)=>{const value=denominations[i];chip.dataset.stake=String(value);chip.textContent=value>=1000000?value/1000000+'m':value>=1000?value/1000+'k':String(value);chip.setAttribute('aria-label','Bet '+value+' coins');chip.title=value.toLocaleString('en-US')+' coins';chip.disabled=locked||value>coins;chip.setAttribute('aria-pressed',String(value===bet))});$('deal').disabled=locked||!Number.isSafeInteger(bet)||bet<2||bet%2!==0||bet>coins;for(const id of ['bet','less','more'])$(id).disabled=locked;$('move-hint').textContent=animating?'The dealer is drawing one card at a time. Your controls will return when the deal finishes.':playing?'Playing hand '+(g.active+1)+' of '+g.hands.length+'. '+(legal.double?'Double adds an equal stake. ':'')+(legal.split?'Pair: splitting is available.':'Splits need a same-rank pair, a free hand slot, and enough coins.'):g.coins<2?'Return to the pond to earn more coins.':g.phase==='done'?'Choose your next stake when you are ready.':'Choose an even-numbered stake. Wins and bets use your fishing wallet.';
  document.querySelector('.table')?.classList.toggle('dealing',animating);
 }
 function animate(type,before,bet){
  const paid=type==='deal'?bet:['double','split'].includes(type)?before.hands[before.active].bet:0;const base={coins:before.coins-paid,dealerCount:Math.min(2,g.dealer.length),handCounts:g.hands.map(h=>h.cards.length),hideHole:true,message:'The dealer is preparing the cards.'};const frames=[];const add=(delay,patch)=>{Object.assign(base,patch);frames.push({delay,state:{...base,handCounts:[...base.handCounts]}})};
  if(type==='deal'){seen=new Set();add(280,{dealerCount:0,handCounts:[0],message:'A fresh round. Here come the cards.'});add(480,{handCounts:[1],message:'Your first card.'});add(480,{dealerCount:1,message:'One for the dealer.'});add(480,{handCounts:[2],message:'Your second card.'});add(650,{dealerCount:2,message:'The dealer’s second card stays face down.'})}
  else if(type==='split'){const counts=g.hands.map(h=>h.cards.length);counts[before.active]=1;counts[before.active+1]=1;add(450,{handCounts:counts,message:'Two hands. One card for each.'});counts[before.active]=2;add(550,{handCounts:counts,message:'A card for your first split hand.'});counts[before.active+1]=2;add(550,{handCounts:counts,message:'A card for your second split hand.'})}
  else if(type==='hit'||type==='double'){const counts=g.hands.map(h=>h.cards.length);counts[before.active]=before.hands[before.active].cards.length;add(400,{handCounts:counts,message:type==='double'?'Doubling your stake. One final card.':'The dealer is drawing your card.'});counts[before.active]++;add(550,{handCounts:counts,message:'A card for your hand.'})}
  else add(550,{message:g.phase==='done'?'Your hands are complete. The dealer turns over the hole card.':'Standing. Moving to the next hand.'});
  if(g.phase==='done'){add(700,{hideHole:false,dealerCount:2,message:'The dealer reveals the hole card.'});for(let i=2;i<g.dealer.length;i++)add(800,{dealerCount:i+1,message:'The dealer draws another card.'});add(600,{message:'Counting the hands…'})}
  const token=++epoch;let index=0;function next(){if(token!==epoch)return;if(index>=frames.length){presentation=null;timer=null;render();return}const frame=frames[index++];presentation=frame.state;render();timer=setTimeout(next,frame.delay)}next();
 }
 function action(type){if(blocked||presentation)return;load();const before=JSON.parse(JSON.stringify(g)),bet=Number($('bet').value);try{localStorage.setItem(key,JSON.stringify(wallet))}catch{blocked=true;g.message='Saving is unavailable. No bet was placed.';render();return}if(type==='deal'){if(!B.deal(g,bet))return}else if(!B.act(g,type))return;save();if(blocked){render();return}animate(type,before,bet)}
 $('name-save').onclick=()=>{if(presentation)return;load();const name=String($('username').value||'').trim().slice(0,24);if(!name){$('name-status').textContent='Enter a name first.';return}wallet.username=name;save();$('name-status').textContent=blocked?'Name could not be saved.':'Name saved.';render()};$('username').value=wallet?.username||'';
 for(const id of ['deal','hit','stand','double','split'])$(id).onclick=()=>action(id);$('bet').oninput=render;$('less').onclick=()=>{if(presentation)return;$('bet').value=Math.max(2,(Number($('bet').value)||2)-2);render()};$('more').onclick=()=>{if(presentation)return;$('bet').value=Math.min(Math.floor(g.coins/2)*2,(Number($('bet').value)||2)+2);render()};window.addEventListener('storage',e=>{if(e.key===key){epoch++;clearTimeout(timer);presentation=null;load();render()}});document.querySelectorAll('[data-stake]').forEach(chip=>chip.onclick=()=>{if(blocked||presentation||g.phase==='play'||Number(chip.dataset.stake)>g.coins)return;$('bet').value=chip.dataset.stake;render()});load();$('username').value=wallet.username;render();
})();
