(()=>{
 const C=Stillwater,B=RangeLensBlackjack,$=id=>document.getElementById(id),key='range-lens-stillwater-v1';let wallet,connection=null,snapshot=null,pending=false,polling=false;const params=new URLSearchParams(location.search);
 function walletLoad(){try{wallet=C.restore(JSON.parse(localStorage.getItem(key)))}catch{wallet=C.fresh()}}
 function walletSave(){try{localStorage.setItem(key,JSON.stringify(wallet));$('online-save').textContent='Shared-table balance saved locally'}catch{$('online-save').textContent='Local saving is unavailable'}}
 function status(t){$('online-status').textContent=t}
 function baseUrl(text){const u=new URL(text);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw Error('Use an http or https table-service address');return u.origin}
 async function permission(base){if(typeof chrome!=='undefined'&&chrome.runtime?.id&&chrome.permissions){const u=new URL(base),pattern=u.protocol+'//'+u.hostname+'/*';if(!await chrome.permissions.request({origins:[pattern]}))throw Error('Connection permission was not granted')}}
 async function api(path,body){const headers={'Content-Type':'application/json'};if(connection)headers.Authorization='Bearer '+connection.session;const response=await fetch(connection?.base+path,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(10000)});const data=await response.json();if(!response.ok)throw Error(data.error||'Table connection failed');return data}
 const card=(c)=>{const el=document.createElement('div');el.className='card'+(c.hidden?' back':[1,2].includes(c.s)?' red':'');el.style.animation='none';if(!c.hidden){const r=document.createElement('span'),s=document.createElement('span');r.textContent=['','A','2','3','4','5','6','7','8','9','10','J','Q','K'][c.r];s.className='suit';s.textContent=['♠','♥','♦','♣'][c.s];el.append(r,s)}return el};
 function render(s){snapshot=s;wallet.coins=s.coins;wallet.online={...connection};walletSave();$('coins').textContent=s.coins;$('lobby').hidden=true;$('table-controls').hidden=false;$('player-name').textContent=wallet.username;const seats=$('seats');seats.replaceChildren();for(const p of s.players){const row=document.createElement('div');row.className='seat';row.textContent=p.name+(p.id===s.self?' (you)':'')+' · '+(p.bet?p.bet+' coins ready':p.online?'At the table':'Away');seats.append(row)}$('dealer-cards').replaceChildren();const dealer=s.game?.dealer||[];dealer.forEach(c=>$('dealer-cards').append(card(c)));$('dealer-total').textContent=dealer.some(c=>c.hidden)?B.value(dealer.filter(c=>!c.hidden)).total+' + ?':dealer.length?B.value(dealer).total:'—';$('hands').replaceChildren();for(const h of s.game?.hands||[]){const row=document.createElement('section');row.className='hand'+(h.active?' active':'');const label=document.createElement('div');label.className='seat-label';label.textContent=h.name+' · '+h.bet+' coins';const total=document.createElement('span');total.textContent=h.cards.length?B.value(h.cards).total:'—';label.append(total);const cards=document.createElement('div');cards.className='cards';h.cards.forEach(c=>cards.append(card(c)));row.append(label,cards);if(h.result){const result=document.createElement('div');result.className='hand-result';result.textContent=h.result+' · '+h.returned+' returned';row.append(result)}$('hands').append(row)}const play=s.phase==='play',busy=s.busy||pending;for(const id of ['hit','stand','double','split'])$(id).disabled=busy||!s.game?.legal[id];$('ready').disabled=busy||play;$('online-bet').disabled=busy||play;$('start').disabled=busy||play||!s.host||!s.players.some(p=>p.bet);$('copy-invite').disabled=false;$('invite-link').value=connection.base+'/?table='+s.id+'&invite='+s.invite;status(s.busy?'The dealer is drawing…':play?s.game.activeOwner===s.self?'Your turn.':'Waiting for '+s.players.find(p=>p.id===s.game.activeOwner)?.name+'…':s.phase==='done'?'Round complete. Choose bets for the next round.':'Invite a friend, choose your bet, and let the host deal.')}
 async function refresh(){if(!connection||polling||pending)return;polling=true;try{render(await api('/api/tables/'+connection.id))}catch(e){status('Connection paused: '+e.message+' · retrying…')}finally{polling=false}}
 async function command(op,extra={}){if(!snapshot||pending)return;pending=true;render(snapshot);try{const data=await api('/api/tables/'+connection.id+'/'+op,{...extra,revision:snapshot.revision});pending=false;render(data)}catch(e){pending=false;status(e.message);await refresh()}}
 async function connect(join){if(pending)return;pending=true;try{walletLoad();const username=String($('online-name').value||'').trim().slice(0,24);if(!username)throw Error('Choose a username first');wallet.username=username;let base,id,invite;if(join){const u=new URL($('join-link').value);base=baseUrl(u.origin);id=u.searchParams.get('table');invite=u.searchParams.get('invite');if(!id||!invite)throw Error('Paste a complete private-table invite link')}else base=baseUrl($('service-url').value);await permission(base);connection={base,session:'',id:id||''};const data=await api(join?'/api/tables/'+id+'/join':'/api/create',{name:wallet.username,coins:wallet.coins,invite});connection.session=data.session;connection.id=data.table.id;pending=false;render(data.table)}catch(e){pending=false;connection=null;status(e.message)}}
 $('create-table').onclick=()=>connect(false);$('join-table').onclick=()=>connect(true);$('ready').onclick=()=>command('bet',{bet:Number($('online-bet').value)});$('start').onclick=()=>command('start');for(const id of ['hit','stand','double','split'])$(id).onclick=()=>command('move',{action:id});$('copy-invite').onclick=async()=>{try{await navigator.clipboard.writeText($('invite-link').value);status('Invite copied. Share it with your friend.')}catch{$('invite-link').select();status('Select and copy the invite link.')}};
 $('resume-table').onclick=async()=>{walletLoad();if(!wallet.online)return;try{await permission(wallet.online.base);connection=wallet.online;await refresh()}catch(e){status(e.message)}};
 walletLoad();$('online-name').value=wallet.username;$('coins').textContent=wallet.coins;$('service-url').value=typeof chrome!=='undefined'&&chrome.runtime?.id?'http://localhost:8780':location.origin;$('resume-table').hidden=!wallet.online;if(params.get('table')&&params.get('invite'))$('join-link').value=location.href;setInterval(refresh,600);
})();
