(()=>{
 if(new URLSearchParams(location.search).get('embed')==='1')document.documentElement.classList.add('embedded');
 const C=Stillwater,$=id=>document.getElementById(id),key='range-lens-stillwater-v1';let p;try{p=C.restore(JSON.parse(localStorage.getItem(key)))}catch{p=C.fresh()}
 let phase='ready',held=false,charge=0,cast=.25,usedBait='worm',fish=null,wait=0,biteAt=0,tension=.2,progress=0,fightTime=0,elapsed=0,last=performance.now(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const save=()=>{try{localStorage.setItem(key,JSON.stringify(p));$('save-state').textContent='Saved on this device'}catch{$('save-state').textContent='Saving unavailable · keep this tab open'}};
 const toast=t=>$('toast').textContent=t;
 const rod=()=>C.rods.find(r=>r.id===p.rod);
 function button(label){$('action').innerHTML='';$('action').textContent=label;const tag=document.createElement('span');tag.textContent='SPACE';$('action').append(tag)}
 function ready(){phase='ready';held=false;charge=0;$('catch-card').hidden=true;$('fight-meters').hidden=true;$('cast-meter').hidden=false;$('cancel').hidden=true;$('cancel').textContent='Bring line in';button('Hold to cast');$('phase-label').textContent='READY TO CAST';$('scene-message').textContent='The pond is yours.';$('hint').textContent='Hold to choose your distance. Release to cast.';$('cast-fill').style.width='0%';renderMenus()}
 function press(){if(held)return;held=true;if(phase==='ready'){phase='charging';charge=.05;toast('');$('phase-label').textContent='FIND YOUR DISTANCE';$('scene-message').textContent='A little farther…'}else if(phase==='bite'){phase='fight';fightTime=0;tension=.24;progress=.04;$('fight-meters').hidden=false;$('cast-meter').hidden=true;$('cancel').hidden=false;$('cancel').textContent='Let fish go';$('phase-label').textContent='FISH ON';$('scene-message').textContent='Steady hands.';button('Hold to reel');$('hint').textContent='Release to ease tension. Reel again when the line relaxes.'}else if(phase==='landed'||phase==='escaped')ready()}
 function release(){if(!held)return;held=false;if(phase==='charging'){cast=Math.max(.12,charge)*rod().reach;usedBait=C.consume(p);save();fish=C.roll(cast>.66?2:cast>.34?1:0,usedBait);phase='waiting';wait=0;biteAt=3+Math.random()*4;$('phase-label').textContent='WAITING FOR A BITE';$('water-label').textContent=cast>.66?'Deep water':cast>.34?'Open water':'Shallow water';$('scene-message').textContent='Let the water settle.';button('Watch the bobber');$('hint').textContent='Small nibbles are a tease. Press when the bobber dips.';$('cancel').hidden=false;$('cast-fill').style.width=cast*100+'%';renderMenus()}}
 function escaped(message){phase='escaped';held=false;$('phase-label').textContent='THE POND KEEPS ITS SECRETS';$('scene-message').textContent=message;$('fight-meters').hidden=true;$('cancel').hidden=true;button('Try another cast');$('hint').textContent='Worms are always free. There is no rush.';renderMenus()}
 function landed(){phase='landed';held=false;const record=C.land(p,fish);save();renderMenus();$('catch-card').hidden=false;$('catch-name').textContent=fish.name;$('catch-rarity').textContent=fish.rarity.toUpperCase()+' CATCH';$('fish-art').setAttribute('fill',fish.color);$('catch-size').textContent=fish.size.toFixed(1)+' cm · safely in your basket';$('catch-value').textContent=fish.value+' coins when sold';$('catch-record').textContent=record?'A new journal record':'Another lovely catch';$('scene-message').textContent='';$('phase-label').textContent='CATCH LANDED';$('fight-meters').hidden=true;$('cancel').hidden=true;button('Cast again');$('hint').textContent='Keep fishing, or sell your basket at the side.'}
 $('action').addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();$('action').setPointerCapture(e.pointerId);press()});$('action').addEventListener('pointerup',release);$('action').addEventListener('pointercancel',()=>{held=false;if(phase==='charging')ready()});$('action').addEventListener('lostpointercapture',release);
 document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!e.target.closest('nav,aside,details,a,#keep,#cancel')){e.preventDefault();press()}});document.addEventListener('keyup',e=>{if(e.code==='Space'){e.preventDefault();release()}});window.addEventListener('blur',()=>{held=false;if(phase==='charging')ready()});
 $('keep').onclick=ready;$('cancel').onclick=()=>{ready();toast('Line brought in. Purchased bait is used on casting.')};$('sell').onclick=()=>{const amount=C.sell(p);save();renderMenus();toast('Sold your catches for '+amount+' coins.')};
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(n=>n.setAttribute('aria-selected',String(n===b)));for(const id of ['basket','shop','book'])$(id).hidden=id!==b.dataset.tab});
 const text=(tag,value)=>{const el=document.createElement(tag);el.textContent=value;return el};
 function item(container,title,description,action,label,disabled=false,selected=false){const row=document.createElement('div');row.className='shop-item';const info=document.createElement('div');info.append(text('strong',title),text('small',description));const b=text('button',label);b.disabled=disabled;b.className=selected?'selected':'';b.onclick=action;row.append(info,b);container.append(row)}
 function renderMenus(){ $('coins').textContent=p.coins;$('loadout').textContent=rod().name+' · '+C.baits.find(b=>b.id===p.bait).name;$('bag-count').textContent=p.bag.length;$('bag-worth').textContent=p.bag.reduce((n,c)=>n+c.value,0)+' coins';$('sell').disabled=!p.bag.length;$('bag-list').replaceChildren();if(!p.bag.length){const empty=document.createElement('div');empty.className='empty';empty.append(text('b','⌁'),text('div','An empty basket. A whole pond of possibilities.'));$('bag-list').append(empty)}
 const grouped=C.fish.map(f=>({...f,catches:p.bag.filter(c=>c.id===f.id)})).filter(f=>f.catches.length);for(const f of grouped){const row=document.createElement('div');row.className='catch-row';const swatch=document.createElement('span');swatch.className='swatch';swatch.style.background=swatch.style.color=f.color;const info=document.createElement('div');info.append(text('strong',f.name+(f.catches.length>1?' ×'+f.catches.length:'')),text('small',Math.max(...f.catches.map(c=>c.size)).toFixed(1)+' cm best'));row.append(swatch,info,text('span',f.catches.reduce((n,c)=>n+c.value,0)+' c'));$('bag-list').append(row)}
 const busy=['charging','waiting','bite','fight'].includes(phase);$('bait-shop').replaceChildren();for(const b of C.baits){const count=b.id==='worm'?'Unlimited':p.stock[b.id]+' left';item($('bait-shop'),b.name,b.desc+' '+count,()=>{if(b.id==='worm'||p.stock[b.id]>0){p.bait=b.id;save();renderMenus()}else if(C.buyBait(p,b.id)){save();renderMenus();toast('Packed five '+b.name.toLowerCase()+' casts.')}},p.bait===b.id?'Selected':b.id==='worm'||p.stock[b.id]>0?'Use':b.price+' coins',busy||(b.id!=='worm'&&!p.stock[b.id]&&p.coins<b.price),p.bait===b.id);if(b.price&&p.stock[b.id]>0)item($('bait-shop'),'Restock '+b.name,'Five more casts.',()=>{if(C.buyBait(p,b.id)){save();renderMenus()}},b.price+' coins',busy||p.coins<b.price)}
 $('rod-shop').replaceChildren();for(const r of C.rods)item($('rod-shop'),r.name,r.desc,()=>{if(p.owned.includes(r.id))p.rod=r.id;else if(!C.buyRod(p,r.id))return;save();renderMenus();toast(r.name+' equipped.')},p.rod===r.id?'Equipped':p.owned.includes(r.id)?'Equip':r.price+' coins',busy||(!p.owned.includes(r.id)&&p.coins<r.price),p.rod===r.id);
 $('discovered').textContent=Object.keys(p.book).length+' / 6';$('book-list').replaceChildren();for(const f of C.fish){const row=document.createElement('div');row.className='book-row';const found=!!p.book[f.id],swatch=document.createElement('span');swatch.className='swatch'+(found?'':' unknown');if(found)swatch.style.background=swatch.style.color=f.color;const info=document.createElement('div');info.append(text('strong',found?f.name:'Undiscovered'),text('small',found?f.rarity+' · record '+p.book[f.id].toFixed(1)+' cm':f.rarity+' · '+(f.id==='eel'?'Deep water, a glow lure, and patience.':'Waiting somewhere in the pond.')));row.append(swatch,info);$('book-list').append(row)} }
 const canvas=$('pond'),g=canvas.getContext('2d');let w=640,h=335;function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);w=r.width;h=r.height;canvas.width=w*d;canvas.height=h*d;g.setTransform(d,0,0,d,0,0)}new ResizeObserver(resize).observe(canvas);
 function ellipse(x,y,rx,ry,color){g.fillStyle=color;g.beginPath();g.ellipse(x,y,rx,ry,0,0,Math.PI*2);g.fill()}
 function draw(t){const motion=reduced?0:t;g.clearRect(0,0,w,h);const sky=g.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#1b363f');sky.addColorStop(.45,'#57716a');sky.addColorStop(.46,'#355954');sky.addColorStop(1,'#15343c');g.fillStyle=sky;g.fillRect(0,0,w,h);ellipse(w*.78,h*.23,17,17,'#c2c7a5');ellipse(w*.79,h*.215,16,16,'#30494f');
 for(let layer=0;layer<3;layer++){g.fillStyle=['#36514f','#2a4848','#1c3c3d'][layer];g.beginPath();g.moveTo(0,h*.46);for(let x=0;x<=w+15;x+=15)g.lineTo(x,h*(.39+layer*.018)-Math.sin(x*.011+layer)*h*.07-Math.sin(x*.031+layer)*h*.012);g.lineTo(w,h*.5);g.lineTo(0,h*.5);g.fill()}
 // Willow silhouettes, water highlights, lily pads, and slow drifting fireflies.
 g.strokeStyle='#193b36';g.lineWidth=3;for(let i=0;i<9;i++){g.beginPath();g.moveTo(w*.02,0);g.quadraticCurveTo(w*(.05+i*.018),h*.08,w*(.05+i*.016)+Math.sin(motion*.5+i)*2,h*(.19+i*.006));g.stroke()}
 for(let i=0;i<22;i++){const x=(i*97%997)/997*w,y=h*.49+(i*41%137)/137*h*.42;g.strokeStyle=i%3?'#b8cec00c':'#b8cec018';g.lineWidth=1;g.beginPath();g.ellipse(x+Math.sin(motion*.3+i)*4,y,12+i%5*7,1.2,0,0,Math.PI*2);g.stroke()}
 for(let i=0;i<8;i++){const x=i<4?w*.08+i*19:w*.89+(i-4)*13,y=h*.7+(i%4)*11;ellipse(x,y,11,3,'#41695a');if(i===2)ellipse(x,y-2,3,2,'#ccb5b5')}
 for(let i=0;i<8;i++){const x=(i*83%487)/487*w+Math.sin(motion*.23+i)*9,y=h*.36+Math.cos(motion*.19+i)*h*.14;ellipse(x,y,1.3,1.3,'#d9d3a0'+(Math.sin(motion+i)>0?'a0':'35'))}
 const bx=w*(.37+cast*.22),by=h*(.82-cast*.26),active=['waiting','bite','fight'].includes(phase),nibble=phase==='waiting'&&wait>biteAt*.4&&Math.sin(wait*5)>.88;
 if(active){const tug=phase==='fight'?Math.sin(motion*5)*5:0,bob=phase==='bite'?7:nibble?3:Math.sin(motion*2)*1.1;g.strokeStyle='#b4c5a567';g.lineWidth=1;g.beginPath();g.moveTo(w*.29,h*.56+(phase==='fight'?tension*h*.04:0));g.quadraticCurveTo(w*.33,h*.57,bx+tug,by+bob);g.stroke();for(let i=0;i<3;i++){const r=((motion*8+i*10)%30)+4;g.strokeStyle='#c4d7c1'+Math.max(0,Math.round((1-r/35)*70)).toString(16).padStart(2,'0');g.beginPath();g.ellipse(bx+tug,by+5,r,r*.22,0,0,Math.PI*2);g.stroke()}ellipse(bx+tug,by+bob,3,5,'#dfb38c');ellipse(bx+tug,by+bob+2,3,2,'#e3e1c9');if(phase==='fight')ellipse(bx+Math.sin(motion*3)*12,by+12,13,3,fish.color+'33')}
 // Draw the bank first, then the entire rod above it so the handle cannot be hidden.
 g.fillStyle='#102d2e';g.beginPath();g.moveTo(0,h);g.lineTo(0,h*.94);g.quadraticCurveTo(w*.13,h*.86,w*.3,h);g.fill();
 const rx=w*.07,ry=h*.95,tx=w*.29,ty=h*.56+(phase==='fight'?tension*h*.04:0);
 g.lineCap='round';g.strokeStyle='#10252b';g.lineWidth=6;g.beginPath();g.moveTo(rx,ry);g.quadraticCurveTo(w*.13,h*.72,tx,ty);g.stroke();g.strokeStyle=p.rod==='moon'?'#ced1e9':p.rod==='willow'?'#bed0ad':'#dfc398';g.lineWidth=3;g.stroke();
 g.strokeStyle='#a8764f';g.lineWidth=7;g.beginPath();g.moveTo(rx,ry);g.lineTo(rx+w*.025,ry-h*.055);g.stroke();ellipse(rx+w*.027,ry-h*.03,5,5,'#c0baa3');ellipse(rx+w*.027,ry-h*.03,2,2,'#28423e');
 for(let i=1;i<=3;i++){const f=i/4;ellipse(rx+(tx-rx)*f,ry+(ty-ry)*f,1.5,2,'#e9e3c3')}

 }
 function frame(now){const dt=Math.min((now-last)/1000,.06);last=now;if(!document.hidden){elapsed+=dt;if(phase==='charging'){charge=Math.min(1,charge+dt*.43);$('cast-fill').style.width=charge*100+'%'}else if(phase==='waiting'){wait+=dt;if(wait>=biteAt){phase='bite';wait=0;$('scene-message').textContent='Fish on!';$('phase-label').textContent='PRESS TO HOOK';button('Hook the fish!');$('hint').textContent='Now! Press the button or Space to hook.'}}else if(phase==='bite'){wait+=dt;if(wait>3.8)escaped('A little too late. It slipped away.')}else if(phase==='fight'){fightTime+=dt;const pulling=Math.sin(fightTime*2.1)> .25,power=fish.strength/rod().control;tension=Math.max(.04,tension+dt*(held?.16+power*(pulling?.13:.01):-.32+power*(pulling?.07:0)));progress=Math.max(0,progress+dt*(held?.10/power:-.024));$('tension-fill').style.width=Math.min(100,tension*100)+'%';$('tension-fill').style.background=tension>.82?'#dc917e':tension>.6?'#d6bc83':'#a4c3a8';$('progress-fill').style.width=progress*100+'%';$('tension-word').textContent=tension>.82?'Ease off!':pulling?'Fish is pulling':'Steady';$('progress-word').textContent=Math.round(progress*100)+'%';$('scene-message').textContent=tension>.82?'Give it some slack.':pulling?'A little tug. Stay patient.':'Bring it closer.';if(tension>=1)escaped('The line snapped. Let the next one run.');else if(progress>=1)landed()}}draw(elapsed);requestAnimationFrame(frame)}
 save();ready();requestAnimationFrame(frame);
})();
