// Private fictional-coin blackjack tables. No third-party dependencies.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');const B=require('../blackjack-core');
const root=path.resolve(__dirname,'..'),file=process.env.TABLE_DATA_FILE||path.join(__dirname,'tables.json');let rooms={};try{rooms=JSON.parse(fs.readFileSync(file,'utf8'))}catch{}
const token=()=>crypto.randomBytes(16).toString('hex'),persist=()=>fs.writeFileSync(file,JSON.stringify(rooms));
function error(message,status=400){const e=Error(message);e.status=status;throw e}const name=s=>String(s||'Angler').trim().slice(0,24)||'Angler';
function player(body){if(!Number.isSafeInteger(body.coins)||body.coins<0||body.coins>1e8)error('Invalid coin balance');return {id:token(),session:token(),name:name(body.name),coins:body.coins,bet:0,lastSeen:Date.now()}}
function settle(r){if(r.game?.phase!=='done'||r.paid)return;r.paid=true;const now=Date.now();for(const p of r.players){p.oldCoins=p.coins;p.showCoinsAt=r.busyUntil||now}for(const h of r.game.hands){const p=r.players.find(p=>p.id===h.owner);p.coins+=h.returned||0}r.phase='done'}
function start(r){const seats=r.players.filter(p=>p.bet>=2&&p.bet<=p.coins);if(!seats.length)error('At least one funded player must choose a bet');const g=B.fresh(0);g.deck=B.shoe();g.phase='play';g.hands=seats.map(p=>({cards:[],bet:p.bet,status:'play',split:false,owner:p.id}));g.dealer=[];const draw=()=>g.deck.pop();const now=Date.now();let n=0;for(const h of g.hands)h.cards.push({...draw(),at:now+(++n)*450});g.dealer.push({...draw(),at:now+(++n)*450});for(const h of g.hands)h.cards.push({...draw(),at:now+(++n)*450});g.dealer.push({...draw(),at:now+(++n)*450});r.busyUntil=now+n*450+500;r.paid=false;r.game=g;r.phase='play';for(const p of seats){p.coins-=p.bet;p.bet=0}for(const h of g.hands)if(B.value(h.cards).total===21)h.status='stand';if(B.value(g.dealer).total===21){B.settle(g);r.busyUntil+=900;settle(r)}else{B.advance(g);settle(r)}r.deadline=r.busyUntil+45000}
function move(r,p,action){if(r.phase!=='play'||Date.now()<r.busyUntil)error('Wait for the deal to finish');const g=r.game,h=g.hands[g.active];if(h.owner!==p.id)error('It is another player’s turn');if(!['hit','stand','split','double'].includes(action))error('Unknown move');const paid=['split','double'].includes(action)?h.bet:0;g.coins=p.coins;const sizes=g.hands.map(h=>h.cards.length),oldDealer=g.dealer.length;if(!B.act(g,action))error('This move is not available');p.coins-=paid;const now=Date.now();r.busyUntil=now+700;for(let i=0;i<g.hands.length;i++)for(let j=0;j<g.hands[i].cards.length;j++)if(!g.hands[i].cards[j].at)g.hands[i].cards[j].at=now+400+(i===g.active?0:250);if(g.phase==='done'){for(let i=oldDealer;i<g.dealer.length;i++)g.dealer[i].at=now+900+(i-oldDealer)*800;r.revealAt=now+650;r.busyUntil=now+1500+Math.max(0,g.dealer.length-oldDealer)*800;settle(r)}r.deadline=r.busyUntil+45000}
function view(r,p){const now=Date.now();p.lastSeen=now;const busy=now<(r.busyUntil||0),g=r.game;let game=null;if(g){const hideHole=r.phase==='play'||busy&&now<(r.revealAt||r.busyUntil);const dealer=g.dealer.filter(c=>!c.at||c.at<=now).map((c,i)=>i===1&&hideHole?{hidden:true}:{r:c.r,s:c.s});const hands=g.hands.map(h=>({owner:h.owner,name:r.players.find(p=>p.id===h.owner)?.name||'Player',bet:h.bet,status:h.status,cards:h.cards.filter(c=>!c.at||c.at<=now).map(c=>({r:c.r,s:c.s})),result:!busy?h.result:null,returned:!busy?h.returned:null,active:r.phase==='play'&&g.hands[g.active]===h}));g.coins=p.coins;game={dealer,hands,activeOwner:r.phase==='play'?g.hands[g.active]?.owner:null,legal:!busy&&g.hands[g.active]?.owner===p.id?B.legal(g):{},deadline:r.deadline}}
 return {id:r.id,revision:r.revision,phase:r.phase,busy,host:r.host===p.id,self:p.id,coins:now<(p.showCoinsAt||0)?p.oldCoins:p.coins,invite:r.invite,players:r.players.map(x=>({id:x.id,name:x.name,bet:x.bet,online:now-x.lastSeen<15000})),game}}
async function body(req){let data='';for await(const chunk of req){data+=chunk;if(data.length>8192)error('Request too large',413)}try{return JSON.parse(data||'{}')}catch{error('Invalid request')}}
const server=http.createServer(async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type,Authorization');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Cache-Control','no-store');if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}try{const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){let payload;const data=req.method==='POST'?await body(req):{};if(url.pathname==='/api/create'&&req.method==='POST'){const p=player(data),r={id:token(),invite:token(),host:p.id,players:[p],phase:'lobby',revision:1,created:Date.now()};rooms[r.id]=r;persist();payload={session:p.session,table:view(r,p)}}else{const match=url.pathname.match(/^\/api\/tables\/([a-f0-9]{32})(?:\/(join|bet|start|move|next))?$/);if(!match)error('Table not found',404);const r=rooms[match[1]];if(!r)error('Table has expired',404);const op=match[2];if(op==='join'&&req.method==='POST'){if(data.invite!==r.invite)error('Invalid invitation',403);if(r.players.length>=4)error('This table is full');if(!['lobby','done'].includes(r.phase))error('Wait until the current round finishes');const p=player(data);r.players.push(p);r.revision++;persist();payload={session:p.session,table:view(r,p)}}else{const session=(req.headers.authorization||'').replace(/^Bearer /,'');const p=r.players.find(p=>p.session===session);if(!p)error('Table session not recognized',403);if(req.method==='POST'){if(data.revision!==r.revision)error('The table changed. Refresh and try again.',409);if(op==='bet'){if(!['lobby','done'].includes(r.phase)||Date.now()<(r.busyUntil||0))error('Wait for this round');if(!Number.isSafeInteger(data.bet)||data.bet<2||data.bet%2||data.bet>p.coins)error('Choose an affordable even bet');p.bet=data.bet}else if(op==='start'){if(r.host!==p.id)error('Only the host can deal');if(!['lobby','done'].includes(r.phase)||Date.now()<(r.busyUntil||0))error('Round already active');start(r)}else if(op==='move')move(r,p,data.action);else error('Unknown table operation');r.revision++;persist()}payload=view(r,p)}}res.setHeader('Content-Type','application/json');return res.end(JSON.stringify(payload))}
 const relative=url.pathname==='/'?'online.html':url.pathname.replace(/^\//,'');if(!['online.html','online.js','casino.css','casino.html','casino.js','blackjack-core.js','stillwater-core.js','stillwater.html','stillwater.css','stillwater.js'].includes(relative))error('Not found',404);res.setHeader('Content-Type',relative.endsWith('.js')?'text/javascript':relative.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(path.join(root,relative)))}catch(e){res.writeHead(e.status||500,{'Content-Type':'application/json'});res.end(JSON.stringify({error:e.status?e.message:'Table service unavailable'}))}});
const interval=setInterval(()=>{for(const r of Object.values(rooms)){if(r.phase==='play'&&Date.now()>r.deadline){const owner=r.game.hands[r.game.active]?.owner,p=r.players.find(p=>p.id===owner);if(p){try{move(r,p,'stand');r.revision++;persist()}catch{}}}}},1000);interval.unref();
if(require.main===module)server.listen(Number(process.env.PORT)||8780,'0.0.0.0',()=>console.log('Stillwater tables listening on port '+(process.env.PORT||8780)));module.exports={server,rooms};

